version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - cd frontend
      - npm install
      
  build:
    commands:
      - echo "Building React application..."
      - echo "Current directory:" && pwd
      - npm run build
      - echo "Build completed on $(date)"
      - echo "Build folder contents:" && ls -la build/
      
  post_build:
    commands:
      - echo "Deploying to S3..."
      - |
        if [ -z "$FRONTEND_BUCKET" ]; then
          FRONTEND_BUCKET="ai-photo-search-frontend-${AWS_ACCOUNT_ID}"
        fi
      - echo "Target bucket: $FRONTEND_BUCKET"
      - echo "Syncing build files to S3..."
      - aws s3 sync build/ s3://${FRONTEND_BUCKET}/ --delete --region $AWS_DEFAULT_REGION
      - echo "Setting content types..."
      - aws s3 cp s3://${FRONTEND_BUCKET}/index.html s3://${FRONTEND_BUCKET}/index.html --content-type "text/html" --metadata-directive REPLACE --region $AWS_DEFAULT_REGION
      - echo "Deployment completed successfully"
      - echo "Website URL: http://${FRONTEND_BUCKET}.s3-website-${AWS_DEFAULT_REGION}.amazonaws.com"

artifacts:
  files:
    - frontend/build/**/*
  name: FrontendArtifact
