version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies for Search Photos Lambda..."
      - cd lambda/search-photos
      - pip install -r requirements.txt -t .
      
  build:
    commands:
      - echo "Building Lambda deployment package..."
      - echo "Current directory:" && pwd
      - echo "Files:" && ls -la
      - zip -r search-photos.zip . -x "*.git*" "buildspec.yml" "*.pyc" "__pycache__/*"
      - echo "Package size:" && du -h search-photos.zip
      
  post_build:
    commands:
      - echo "Updating Lambda function..."
      - |
        if [ -z "$FUNCTION_NAME" ]; then
          FUNCTION_NAME="ai-photo-search-search-photos"
        fi
      - echo "Function name: $FUNCTION_NAME"
      - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://search-photos.zip --region $AWS_DEFAULT_REGION
      - echo "Waiting for function update to complete..."
      - aws lambda wait function-updated --function-name $FUNCTION_NAME --region $AWS_DEFAULT_REGION
      - echo "Publishing new version..."
      - aws lambda publish-version --function-name $FUNCTION_NAME --region $AWS_DEFAULT_REGION
      - echo "Build completed on $(date)"

artifacts:
  files:
    - lambda/search-photos/search-photos.zip
  name: SearchPhotosArtifact
